'use client'

import { useState, useRef, useMemo, useEffect } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import toast from 'react-hot-toast'
import { useCategories, useAreas, useCountries } from '@/hooks'

interface UploadedImage {
  fileName: string
  url: string
  path: string
}

// Icon mapping based on keywords
const getIconFromName = (name: string, type: 'category' | 'city'): string => {
  const lowerName = name.toLowerCase()
  
  if (type === 'city') {
    return 'location_city'
  }
  
  // Category icons based on keywords
  if (lowerName.includes('tech') || lowerName.includes('technology') || lowerName.includes('digital')) {
    return 'computer'
  }
  if (lowerName.includes('startup') || lowerName.includes('business') || lowerName.includes('company')) {
    return 'rocket_launch'
  }
  if (lowerName.includes('sport') || lowerName.includes('fitness') || lowerName.includes('health')) {
    return 'sports_basketball'
  }
  if (lowerName.includes('education') || lowerName.includes('learn') || lowerName.includes('school')) {
    return 'school'
  }
  if (lowerName.includes('travel') || lowerName.includes('trip') || lowerName.includes('tour')) {
    return 'flight'
  }
  if (lowerName.includes('food') || lowerName.includes('restaurant') || lowerName.includes('cooking')) {
    return 'restaurant'
  }
  if (lowerName.includes('music') || lowerName.includes('art') || lowerName.includes('culture')) {
    return 'palette'
  }
  
  // Default icon
  return 'folder'
}

// Color class mapping
const colorClasses = [
  'bg-indigo-900/40',
  'bg-sky-200/40',
  'bg-blue-600/30',
  'bg-orange-500/20',
  'bg-yellow-500/20',
  'bg-red-400/30',
  'bg-emerald-500/20',
  'bg-purple-500/20',
  'bg-pink-500/20',
  'bg-cyan-500/20',
]

const getColorClass = (name: string, type: 'category' | 'city'): string => {
  // Use hash of name to consistently pick a color
  let hash = 0
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash)
  }
  const index = Math.abs(hash) % colorClasses.length
  
  if (type === 'city') {
    // Cities get green/emerald colors
    return 'bg-emerald-500/20'
  }
  
  return colorClasses[index]
}

export default function AdminNewCategoryPage() {
  const router = useRouter()
  const { createCategory, creating, error: createError } = useCategories()
  const { areas, loading: areasLoading, fetchAreas } = useAreas()
  const { countries, loading: countriesLoading, fetchCountries } = useCountries()
  const [type, setType] = useState<'category' | 'city'>('category')
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [imageUrl, setImageUrl] = useState('')
  const [areaId, setAreaId] = useState('')
  const [countryId, setCountryId] = useState('')
  const [uploading, setUploading] = useState(false)
  const [uploadError, setUploadError] = useState<string | null>(null)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [uploadedImages, setUploadedImages] = useState<UploadedImage[]>([])
  const [loadingImages, setLoadingImages] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  // Fetch areas and countries on mount
  useEffect(() => {
    fetchAreas()
    fetchCountries()
  }, [fetchAreas, fetchCountries])

  // Load uploaded images
  const loadUploadedImages = async () => {
    setLoadingImages(true)
    try {
      const response = await fetch('/api/upload/list')
      const result = await response.json()
      if (result.success) {
        setUploadedImages(result.data || [])
      }
    } catch (err) {
      console.error('Error loading uploaded images:', err)
    } finally {
      setLoadingImages(false)
    }
  }

  // Load images when opening picker
  useEffect(() => {
    if (showImagePicker) {
      loadUploadedImages()
    }
  }, [showImagePicker])

  // Auto-generate id, icon, and colorClass
  const autoGenerated = useMemo(() => {
    if (!name) {
      return {
        id: '',
        icon: '',
        colorClass: '',
      }
    }

    const generatedId = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
    const generatedIcon = getIconFromName(name, type)
    const generatedColorClass = getColorClass(name, type)

    return {
      id: generatedId,
      icon: generatedIcon,
      colorClass: generatedColorClass,
    }
  }, [name, type])

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    // Validate file type
    if (!file.type.startsWith('image/')) {
      setUploadError('Vui lòng chọn file ảnh')
      return
    }

    // Validate file size (5MB)
    if (file.size > 5 * 1024 * 1024) {
      setUploadError('File không được vượt quá 5MB')
      return
    }

    setUploading(true)
    setUploadError(null)

    try {
      const formData = new FormData()
      formData.append('file', file)

      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      })

      const result = await response.json()

      if (!response.ok || !result.success) {
        throw new Error(result.error || 'Upload failed')
      }

      setImageUrl(result.url)
      setUploadError(null)
      // Refresh uploaded images list if picker is open
      if (showImagePicker) {
        loadUploadedImages()
      }
    } catch (err: any) {
      setUploadError(err.message || 'Lỗi khi upload ảnh')
      console.error('Upload error:', err)
    } finally {
      setUploading(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!name || !imageUrl) {
      toast.error('Vui lòng điền đầy đủ các trường bắt buộc (Tên và Hình Ảnh)')
      return
    }

    if (type === 'city' && (!areaId || !countryId)) {
      toast.error('Vui lòng chọn khu vực và quốc gia cho thành phố')
      return
    }

    const newCategory = await createCategory({
      id: autoGenerated.id,
      name,
      icon: autoGenerated.icon,
      image: imageUrl,
      colorClass: autoGenerated.colorClass,
      description: description || undefined,
      isCity: type === 'city',
      areaId: type === 'city' ? areaId : null,
      countryId: type === 'city' ? countryId : null,
    })

    if (newCategory) {
      toast.success('Tạo danh mục/thành phố thành công!')
      router.push('/admin/categories')
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-gray-900">
            Tạo Danh Mục/Thành Phố Mới
          </h1>
          <p className="mt-1 text-sm text-gray-500">
            Tạo danh mục hoặc thành phố mới cho blog.
          </p>
        </div>
        <Link
          href="/admin/categories"
          className="text-sm text-gray-500 hover:text-gray-800 inline-flex items-center gap-1"
        >
          <span className="material-icons-outlined text-sm">arrow_back</span>
          Quay lại danh sách
        </Link>
      </div>

      <form onSubmit={handleSubmit} className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Loại</label>
          <select
            value={type}
            onChange={(e) => setType(e.target.value as 'category' | 'city')}
            className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 bg-white focus:ring-primary focus:border-primary"
          >
            <option value="category">Danh Mục</option>
            <option value="city">Thành Phố</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Tên *</label>
          <input
            type="text"
            required
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 focus:ring-primary focus:border-primary"
            placeholder="Tên danh mục hoặc thành phố"
          />
          {name && (
            <div className="mt-2 p-3 bg-gray-50 rounded-lg border border-gray-200">
              <div className="text-xs text-gray-600 space-y-1">
                <div className="flex items-center gap-2">
                  <span className="font-medium">ID:</span>
                  <span className="font-mono text-gray-900">{autoGenerated.id}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="font-medium">Icon:</span>
                  <span className="font-mono text-gray-900">{autoGenerated.icon}</span>
                  <span className="material-icons-outlined text-sm text-gray-400">{autoGenerated.icon}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="font-medium">Màu:</span>
                  <span className="font-mono text-gray-900">{autoGenerated.colorClass}</span>
                  <span className={`w-4 h-4 rounded ${autoGenerated.colorClass} border border-gray-300`}></span>
                </div>
              </div>
            </div>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Mô tả</label>
          <textarea
            rows={3}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 focus:ring-primary focus:border-primary"
            placeholder="Mô tả"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Hình Ảnh *</label>
            <div className="space-y-2">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={imageUrl}
                  onChange={(e) => setImageUrl(e.target.value)}
                  className="flex-1 rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 focus:ring-primary focus:border-primary"
                  placeholder="URL hình ảnh hoặc chọn từ ảnh đã upload"
                />
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleFileUpload}
                  className="hidden"
                  id="image-upload"
                />
                <label
                  htmlFor="image-upload"
                  className="inline-flex items-center gap-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50 cursor-pointer"
                >
                  <span className="material-icons-outlined text-sm">
                    {uploading ? 'hourglass_empty' : 'upload'}
                  </span>
                  <span>{uploading ? 'Đang tải...' : 'Upload'}</span>
                </label>
                <button
                  type="button"
                  onClick={() => setShowImagePicker(true)}
                  className="inline-flex items-center gap-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50"
                >
                  <span className="material-icons-outlined text-sm">image</span>
                  <span>Chọn ảnh</span>
                </button>
              </div>
              {uploadError && (
                <p className="text-xs text-red-600">{uploadError}</p>
              )}
              {imageUrl && (
                <div className="relative rounded-lg overflow-hidden border border-gray-200 bg-gray-50 max-w-xs">
                  <img
                    src={imageUrl}
                    alt="Preview"
                    className="w-full h-auto max-h-32 object-contain"
                  />
                </div>
              )}
            </div>
        </div>

        {/* City-specific fields */}
        {type === 'city' && (
          <div className="space-y-4 border-t pt-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Khu Vực</label>
              <select
                value={areaId}
                onChange={(e) => setAreaId(e.target.value)}
                disabled={areasLoading}
                className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 bg-white focus:ring-primary focus:border-primary disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <option value="">
                  {areasLoading ? 'Đang tải...' : 'Chọn khu vực'}
                </option>
                {areas.map((area) => (
                  <option key={area.id} value={area.id}>
                    {area.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Quốc Gia</label>
              <select
                value={countryId}
                onChange={(e) => setCountryId(e.target.value)}
                disabled={countriesLoading}
                className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 bg-white focus:ring-primary focus:border-primary disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <option value="">
                  {countriesLoading ? 'Đang tải...' : 'Chọn quốc gia'}
                </option>
                {countries.map((country) => (
                  <option key={country.id} value={country.id}>
                    {country.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
        )}

        {/* Error Display */}
        {createError && (
          <div className="rounded-lg border border-red-200 bg-red-50 p-3">
            <p className="text-sm text-red-600">{createError}</p>
          </div>
        )}

        <div className="flex gap-2 pt-4 border-t">
          <button
            type="submit"
            disabled={creating || uploading}
            className="inline-flex items-center justify-center rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {creating ? 'Đang tạo...' : 'Tạo Mới'}
          </button>
          <Link
            href="/admin/categories"
            className="inline-flex items-center justify-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 shadow-sm hover:bg-gray-50"
          >
            Hủy
          </Link>
        </div>
      </form>

      {/* Image Picker Modal */}
      {showImagePicker && (
        <div 
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
          onClick={() => setShowImagePicker(false)}
        >
          <div 
            className="bg-white rounded-2xl shadow-xl max-w-4xl w-full mx-4 max-h-[80vh] overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-6 border-b border-gray-200 flex items-center justify-between">
              <h2 className="text-lg font-semibold text-gray-900">Chọn Ảnh Đã Upload</h2>
              <div className="flex items-center gap-2">
                <button
                  onClick={loadUploadedImages}
                  disabled={loadingImages}
                  className="inline-flex items-center gap-1 rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 hover:bg-gray-50 disabled:opacity-50"
                  title="Làm mới danh sách"
                >
                  <span className="material-icons-outlined text-sm">refresh</span>
                  <span>Làm mới</span>
                </button>
                <button
                  onClick={() => setShowImagePicker(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <span className="material-icons-outlined">close</span>
                </button>
              </div>
            </div>
            
            <div className="flex-1 overflow-y-auto p-6">
              {loadingImages ? (
                <div className="text-center py-12">
                  <div className="text-sm text-gray-500">Đang tải danh sách ảnh...</div>
                </div>
              ) : uploadedImages.length === 0 ? (
                <div className="text-center py-12">
                  <span className="material-icons-outlined text-4xl text-gray-300 mb-2">image</span>
                  <div className="text-sm text-gray-500">Chưa có ảnh nào được upload</div>
                </div>
              ) : (
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                  {uploadedImages.map((img) => (
                    <div
                      key={img.fileName}
                      onClick={() => {
                        setImageUrl(img.url)
                        setShowImagePicker(false)
                      }}
                      className={`relative group cursor-pointer rounded-lg overflow-hidden border-2 transition-all ${
                        imageUrl === img.url
                          ? 'border-primary ring-2 ring-primary'
                          : 'border-gray-200 hover:border-primary'
                      }`}
                    >
                      <div className="aspect-square bg-gray-100">
                        <img
                          src={img.url}
                          alt={img.fileName}
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center">
                        <span className="material-icons-outlined text-white opacity-0 group-hover:opacity-100 transition-opacity">
                          check_circle
                        </span>
                      </div>
                      {imageUrl === img.url && (
                        <div className="absolute top-2 right-2">
                          <span className="material-icons-outlined text-primary bg-white rounded-full">
                            check_circle
                          </span>
                        </div>
                      )}
                      <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-2">
                        <p className="text-xs text-white truncate">{img.fileName}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
            
            <div className="p-4 border-t border-gray-200 flex justify-end">
              <button
                type="button"
                onClick={() => setShowImagePicker(false)}
                className="inline-flex items-center justify-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50"
              >
                Đóng
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

